---
title: "Assessing Corelogic Data Quality"
author: "Kate Ham"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(readxl) # part of the tidyverse

# Parameters

## Files

# rds_file <- "Z:/.ir.stanford.edu/users/k/h/kham101/Documents/dcl-c01-kham101/corelogic_tax_bayarea.rds"

cl_alameda <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_alameda.rds"
cl_contracosta <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_contracosta.rds"
cl_marin <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_marin.rds"
cl_napa <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_napa.rds"
cl_sanfrancisco <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_sanfrancisco.rds"
cl_sanmateo <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_sanmateo.rds"
cl_santaclara <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_santaclara.rds"
cl_solano <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_solano.rds"
cl_sonoma <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_sonoma.rds"

xlsx_file <- "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data-raw/Bulk_Tax_Current_Layout w parcel level lat long_03102016.xlsx"

## Variables

BAY_AREA <- 
  c(
    cl_alameda,
    cl_contracosta,
    cl_marin,
    cl_napa,
    cl_sanfrancisco,
    cl_sanmateo,
    cl_santaclara,
    cl_solano,
    cl_sonoma
  )

## Functions

recode_county2 <- function(file) {
  file %>% 
    recode(
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_alameda.rds" = "alameda",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_contracosta.rds" = "contracosta",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_marin.rds" = "marin",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_napa.rds" = "napa",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_sanfrancisco.rds" = "sanfrancisco",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_sanmateo.rds" = "sanmateo",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_santaclara.rds" = "santaclara",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_solano.rds" = "solano",
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_sonoma.rds" = "sonoma"
    )
}

```


## filter for best qual vars
```{r}
cl_filter_na <- function(cl_county) {
  cl_county %>% 
  read_rds() %>% 
  summarize_all(~ sum(is.na(.))) %>% 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "na_count") %>% 
  mutate(na_prop = na_count / nrow(cl_county %>% read_rds())) %>% 
  filter(na_prop <= 0.25) %>% 
  arrange(na_prop) %>% 
  write_rds(
    str_glue(
      "C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/cl_na_", 
      "{recode_county2(cl_county)}", 
      ".rds"
    )
  )
}
```

```{r}
walk(BAY_AREA, cl_filter_na)
```

```{r}
#all9 <- rbind(cl_alameda, cl_contracosta, cl_marin, cl_napa, cl_sanfrancisco, cl_sanmateo, cl_santaclara, cl_solano, cl_sonoma)

best_vars <- 
  all9 %>% 
  summarize_all(~ sum(is.na(.))) %>% 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "na_count") %>% 
  mutate(na_prop = na_count / nrow(all9)) %>% 
  filter(na_prop <= 0.25) %>% 
  group_by(variable) %>% 
  summarize(
    na_count = sum(na_count)
  ) %>% 
  arrange(na_count) %>% 
  .$variable %>%
  write_rds("C:/Users/katea/GitHub/dcl-2020-01/kate/c01-own/data/best_vars.rds")
```



```{r}

  
```

```{r}
cl_napa %>% 
  summarize_all(~ sum(is.na(.))) %>% 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "na_count")
```


### Subsection
```{r}
corelogic %>% 
  filter(`PROPERTY INDICATOR` %in% c("00", "13")) %>% 
  count(`LAND USE`)
```
114 is common area, 999 is misc, 867 is easement, and 754 is lake/river/beach. 266 is service station. probably not useful to us.

## Residential Parcels Only
```{r}
corelogic %>% 
  filter(`PROPERTY INDICATOR` %in% c(10, 11)) %>% 
  #count(`LAND USE`)
```

## Recode land use with data dictionary Excel file join
```{r}
data_dic_luse <- 
  read_excel(xlsx_file, sheet = "LUSE") %>% 
  transmute(
    luse_code = as.double(`CdVal`),
    luse_desc = `CdDesc`
  )
```

## Select good qual vars and recode
```{r}
corelogic %>% 
  filter(`PROPERTY INDICATOR` %in% c(10, 11)) %>% 
  left_join(data_dic_luse, by = c("LAND USE" = "luse_code")) %>% 
  select(corelogic_na$variable)
```

```{r}
# 
# spec(cl_napa)
# problems(cl_napa) # %>% count(col) %>% pull(col)
```

